[package]
name = "app-wheel"
version = "0.1.0"
authors = ["arivwalia@gmail.com"]
edition = "2021"

[dependencies]
egui = "0.23"
egui-winit = "0.23"
winit = "0.28"
device_query = "0.2"
     # For monitoring keyboard inputs

